# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('main', '0002_book_reserved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('book_tracked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.User')),
            ],
        ),
    ]
