# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181025_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktracked',
            name='book_tracked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_views', to='main.Book'),
        ),
        migrations.AlterField(
            model_name='booktracked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='login_register.User'),
        ),
    ]
